services:
  ecommerceaspnet.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - test
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    volumes:
     - dbsql:/opt/var/mssql
    networks: 
    - test
    ports:
     - "1433:1433"
    environment:
     MSSQL_SA_PASSWORD: 
     ACCEPT_EULA: 'Y'
    user: root

networks:
  test:

volumes:
  dbsql:
  